### ISSUE TITLE
Create an Identical Deployment Canary CKAD

### ISSUE THREAD

**Issue by PracticeExams** [PracticeExams/create-an-identical-deployment-canary-ckad#1]
Creating an identical deployment with a canary release is a common task in Kubernetes. It helps you deploy updates to a small subset of users to verify stability before rolling out changes to the entire deployment.

To **[Create an Identical Deployment Canary CKAD](https://prepbolt.com/paths/linux-foundation/questions/ckad)** release in Kubernetes, deploy the primary and canary versions with different replica counts. Use services or ingress for traffic splitting. Gradually increase traffic to the canary version while monitoring performance. The `exec` keyword is essential for debugging container behavior and troubleshooting issues within the pods.

Here’s a guide for doing this:

### Steps to Create an Identical Deployment with a Canary Release

1. **Create Your Primary Deployment:**
   Ensure you have your main deployment up and running. For example:

   ```yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: primary-deployment
   spec:
     replicas: 3
     selector:
       matchLabels:
         app: my-app
     template:
       metadata:
         labels:
           app: my-app
       spec:
         containers:
         - name: my-app-container
           image: my-app:1.0
           ports:
           - containerPort: 80
   ```

2. **Create a Canary Deployment:**
   Create a second deployment with the same specifications but a smaller number of replicas. This will represent the updated version you’re testing. For example:

   ```yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: canary-deployment
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: my-app-canary
     template:
       metadata:
         labels:
           app: my-app-canary
       spec:
         containers:
         - name: my-app-container
           image: my-app:1.1
           ports:
           - containerPort: 80
   ```

3. **Use a Service to Split Traffic:**
   Use a service to route traffic between the primary and canary deployments. For example:

   ```yaml
   apiVersion: v1
   kind: Service
   metadata:
     name: my-app-service
   spec:
     selector:
       app: my-app
     ports:
     - protocol: TCP
       port: 80
       targetPort: 80
   ---
   apiVersion: v1
   kind: Service
   metadata:
     name: my-app-canary-service
   spec:
     selector:
       app: my-app-canary
     ports:
     - protocol: TCP
       port: 80
       targetPort: 80
   ```

4. **Configure Traffic Splitting:**
   Use an ingress or a service mesh (e.g., Istio or Linkerd) to route a small percentage of traffic to the canary deployment.

   **Example with an Ingress:**
   ```yaml
   apiVersion: networking.k8s.io/v1
   kind: Ingress
   metadata:
     name: my-app-ingress
   spec:
     rules:
     - host: my-app.example.com
       http:
         paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: my-app-service
               port:
                 number: 80
         - path: /canary
           pathType: Prefix
           backend:
             service:
               name: my-app-canary-service
               port:
                 number: 80
   ```

5. **Monitor and Verify:**
   - Use monitoring tools like Prometheus or Grafana to ensure the canary release is performing as expected.
   - Check logs and metrics for errors or anomalies.

6. **Gradually Increase Traffic:**
   If the canary deployment works as expected, gradually increase its replicas and redirect more traffic to it.

Would you like a tailored YAML script for a specific configuration?
